# Generated by Django 4.2.3 on 2023-07-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='1000', max_length=255),
            preserve_default=False,
        ),
    ]
