# Generated by Django 4.2.3 on 2023-07-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
    ]
