# Generated by Django 4.2.3 on 2023-07-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merge_0003_auto_20230705_1142_0004_auto_20210610_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
